### ISSUE TITLE
jest code coverage - uncovered lines

### ISSUE THREAD

**Issue by sebastian-meier** [mihar-22/svelte-jester#43]
When i use `jest --coverage`, all tests pass, but some branches do not reach 100% and produce uncovered lines.

Example from a [boilerplate](https://github.com/sebastian-meier/svelte-boilerplate/) of mine.
![image](https://user-images.githubusercontent.com/302789/116705381-c34da400-a9cc-11eb-81bb-b441b018b99a.png)

To reproduce a very simple component:

**button.svelte**
```svelte
<script lang="ts">
  export let label = '';
</script>

<button>{label}</button>
```

**button.test.ts**
```typescript
import { render } from '@testing-library/svelte'
import Button from '../views/components/button.svelte'

test('button - props', () => {
  const label = 'Click';
  const setLabel = 'New Label';
  const { getByText, component } = render(Button, { label });

  expect(() => getByText(label)).not.toThrow();

  component.label = setLabel;
  expect(() => getByText(setLabel)).not.toThrow();

  component.label = undefined;
  expect(() => getByText('undefined')).toThrow();

  component.label = null;
  expect(() => getByText('null')).toThrow();

  delete component.label;
  expect(() => getByText('null')).toThrow();
})

test('button - no prop', () => {
  global.console.warn = jest.fn()
  const { container } = render(Button);
  expect(container.innerHTML).toBe('<div></div>')
expect(console.warn).toBeCalled()
})

test('button - false prop', () => {
  global.console.warn = jest.fn()
  const {container} = render(Button, { falseProp: false });
  expect(container.innerHTML).toBe('<div></div>')
  expect(console.warn).toBeCalled()
})
```

It's possible to increase the component's coverage, by introducing the following:
**button.svelte**
```svelte
<script lang="ts">
  export let label = '';
  $: cLabel = label || '';
</script>

{#if cLabel}
<button>{cLabel}</button>
{/if}
```

But even then one *else path not taken* remains. Which to me makes no sense at that point:
![image](https://user-images.githubusercontent.com/302789/116706257-bc736100-a9cd-11eb-9105-caca60f3e908.png)

Using svelte-jester v1.5.0
Full setup can be found in this [repo](https://github.com/sebastian-meier/svelte-boilerplate/)

**Comment by yunseop-bbrick** [comment]
I have same issue..

**Comment by sebastianrothe** [comment]
Can you please retry with the latest version and jest 27+?

**Comment by sebastian-meier** [comment]
Upgrading to 27 led to a lot of problems. I think i could resolve most of them, but the last problem depends on this issue being solved: https://github.com/mihar-22/svelte-jester/issues/25 As soon as this one is resolved i will try again.

**Comment by sebastian-meier** [comment]
So i have downloaded a copy of the current dev version and got it working. But sadly the problem remains.

**Comment by enjoythelive1** [comment]
The same has happen to me, specifically with the `{#if}` blocks that do not have `{:else}`.

**Comment by sebastianrothe** [comment]
> Upgrading to 27 led to a lot of problems. I think i could resolve most of them, but the last problem depends on this issue being solved: https://github.com/mihar-22/svelte-jester/issues/25 As soon as this one is resolved i will try again.

#25 is resolved, already

**Comment by sebastian-meier** [comment]
Sorry, yes its resolved, BUT, the last few comments on #25 highlight that the next release 2.1.3 will completely fix it. I have used the current dev state for testing not 2.1.2. Anyhow, 27 sadly did not fix the problem.

**Comment by tveronezi** [comment]
Where do you guys think the problem is? I can't find a place in the code it could be. Maybe it's outside this project? Maybe `svelte/compiler`?

**Comment by sebastianrothe** [comment]
I think so too. It is either jest or svelte.
